user_model_project/user_model_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from usermodel_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^usermodel_app/',include('usermodel_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special')
]

user_model_project/usermodel_app/urls.py
from django.conf.urls import url
from usermodel_app import views

#TEMPLAE URLS!
app_name ='usermodel_app'


urlpatterns=[
        url(r'^register/$',views.register,name='register'),
        url(r'^user_login/$',views.user_login,name='user_login'),
]

user_model_project/usermodel_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #additional classes
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username

user_model_project/usermodel_app/forms.py
from django import forms
from django.contrib.auth.models import User
from usermodel_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

user_model_project/usermodel_app/views.py
from django.shortcuts import render
from usermodel_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'usermodel_app/index.html')

@login_required
def special(request):
    return HttpResponse("You're Logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)  #hashing the password
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'usermodel_app/registration.html',
                                {'user_form':user_form,
                                 'profile_form':profile_form,
                                 'registered':registered})


def user_login(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACITVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request,'usermodel_app/login.html',{})

user_model_project/templates/usermodel_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="new_landing_page.html">Django</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'usermodel_app:register' %}">Register</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'usermodel_app:user_login' %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Explore
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="https://www.youtube.com">Youtube</a>
              <a class="dropdown-item" href="https://www.google.com">Google Search</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="https://www.facebook.com">Facebook</a>
            </div>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">

    {% block body_block %}
    {% endblock %}

    </div>

  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.7/js/tether.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" ></script>

</html>

user_model_project/templates/usermodel_app/index.html
{% extends "usermodel_app/base.html"  %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django User Model Homepage</h1>
</div>

{% endblock %}

user_model_project/templates/usermodel_app/login.html
{% extends 'usermodel_app/base.html' %}
{% block body_block %}


<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'usermodel_app:user_login' %}" method="post">

  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter Username">
<br>
  <label for="password">Password:</label>
  <input type="password" name="password" placeholder="password">
<br>
<span>              </span>  <input type="submit" name="" value="Login">

  </form>
</div>
{% endblock %}

user_model_project/templates/usermodel_app/registration.html
{% extends 'usermodel_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
      <h1>Thank you for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>
{% endblock %}