template_project/demo_template_app/urls.py
from django.conf.urls import url
from . import views #from current app



#TEMPLATE TAGGING
app_name = 'demo_template_app'

urlpatterns = [

        url(r'^relative/$',views.relative,name='relative'),
        url(r'^other/$',views.other,name='other'),

]

template_project/template_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from demo_template_app import views
urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^template_app/',include('demo_template_app.urls')),
    url(r'^admin/', admin.site.urls),
]

template_project/demo_template_app/models.py
from django.db import models

# Create your models here

template_project/demo_template_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'demo_template_app/index.html',context_dict)

def other(request):
    return render(request,'demo_template_app/other.html')

def relative(request):
    return render(request,'demo_template_app/relative_url_templates.html')

template_project/templates/demo_template_app/base.html
<!DOCTYPE html>
  <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">

    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo_template_app:other' %}">Other</a>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      <span class="navbar-text">
        Navbar text with an inline element
      </span>-->
    </div>
  </div>
</nav>


    <div class="container">

      {% block body_block %}

      {% endblock %}

    </div>

  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.7/js/tether.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" ></script>
</html>

template_project/templates/demo_template_app/index.html
<!DOCTYPE html>
{% extends 'demo_template_app/base.html' %}
{% block body_block %}
<h1>Index Page</h1>
<h1>Template Inheritance</h1>
<h1>{{ text|cut:'hell' }}</h1>
<h1>{{ number|add:"99" }}</h1>
{% endblock %}

template_project/templates/demo_template_app/other.html
<!DOCTYPE html>
{% extends "demo_template_app/base.html" %}
  {% block body_block %}
          <h1>Welocome to Other</h1>
          <h2>Template Inheritance!!!</h2>
          {% endblock %}

template_project/templates/demo_template_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <title></title>
  </head>
  <body>

      <div class="container">
        <div class="jumbotron">
          <h1>Welcome to URL TEMPLATES</h1>
          <a href="{% url 'demo_template_app:other' %}">The Other Page</a>
      <br>    <a href="{% url 'admin:index' %}">Link to Admin</a>
            <br>
            <a href="{% url 'index' %}">Link to Index</a>
        </div>
      </div>

  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.7/js/tether.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" ></script>

</html>